title: Keertana A/P Subramaniam
logo: assets/cropped_circle_image.png
# description: Data Analytics student at Sunway University | Dean’s List | SAS Board of Director
show_downloads: true
theme: jekyll-theme-minimal
