title: Keertana A/P Subramaniam
logo: assets/cropped_circle_image.png
description: >
  Bachelor of Information Systems (Data Analytics) student at Sunway University, Selangor.  
  CGPA: 3.81 | Dean’s List Award (4 semesters).  
  Actively involved in Sunway Analytics Society (SAS), contributing to data analytics events and student engagement.
  Experienced in leadership and volunteering through past involvement with AIESEC.
  Skilled in Excel, Python, SQL, and SAS.
  Available for internship from 19 January 2026 to 17 April 2026.  
show_downloads: true
theme: jekyll-theme-minimal
